// flow-typed signature: 07afd307cd9092342abbb4333d215b41
// flow-typed version: <<STUB>>/redux-mock-store_v^1.2.3/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-mock-store'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "redux-mock-store" {
  declare module.exports: (
    middlewares?: Array<*>
  ) => (
    getState?: Object | Function
  ) => {
    getState(): Object,
    getActions(): Array<Object>,
    dispatch(action: Object): Promise<Object>,
    clearActions(): void,
    subscribe(callback: Function): Function,
    replaceReducer(nextReducer: Function): void
  };
}
